#!/bin/bash
# ============================================================================
# manifest.sh — uninstall manifest helpers
#
# Each dispatcher (init.sh, init-scaffold.sh) records the files it stamped
# into a per-dispatcher manifest under .claude/. A later --uninstall call
# reads that manifest and reverses the operation: rm each listed file, then
# prune any now-empty parent directories, then drop the manifest itself.
#
# Two separate manifests so the two scaffolders coexist in the same workspace
# and uninstall independently:
#   .claude/.scaffold-manifest-rules.txt      (written by init.sh)
#   .claude/.scaffold-manifest-scaffold.txt   (written by init-scaffold.sh)
#
# Manifest format (see manifest_rows for every version):
#   # ... comment / metadata lines beginning with '#'
#   v1 (init.sh):          <sha256><TAB><relative path>
#   v2 (init-scaffold.sh): <sha256|-><TAB><rel><TAB><origin><TAB><backup rel|->
#
# Usage:
#   source "${SCRIPT_DIR}/lib/manifest.sh"
#   manifest_write "${TARGET_DIR}/.claude/.scaffold-manifest-foo.txt" \
#                  "Generated by foo.sh" \
#                  "Platform: $PLATFORM" \
#                  -- \
#                  "${CREATED_FILES[@]}"
#   manifest_uninstall "${TARGET_DIR}/.claude/.scaffold-manifest-foo.txt"
# ============================================================================

set -euo pipefail
# shellcheck source=safe-path.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/safe-path.sh"
# shellcheck source=txn.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/txn.sh"

# ----------------------------------------------------------------------------
# manifest_write <manifest-path> <header-1> [<header-N>...] -- <file-1> [<file-N>...]
#
# Header lines are emitted prefixed with '# ' for readability + so the
# uninstall reader skips them. Then '--' marks the end of headers and the
# remaining positional args are the absolute file paths to record.
# ----------------------------------------------------------------------------
# manifest_hash <file> — CRLF-normalised sha256 (matches the harness lock).
manifest_hash() {
  local sha
  if command -v sha256sum >/dev/null 2>&1; then sha="sha256sum"; else sha="shasum -a 256"; fi
  tr -d '\r' < "$1" | $sha | cut -c1-64
}

manifest_write() {
  local manifest_path="$1"
  shift

  mkdir -p "$(dirname "$manifest_path")"

  {
    while [[ $# -gt 0 && "$1" != "--" ]]; do
      printf '# %s\n' "$1"
      shift
    done
    # Consume the '--' separator if present.
    [[ "${1:-}" == "--" ]] && shift

    # v1.0 format: "<sha256>\t<path relative to the target root>". Relative
    # paths survive moving/cloning the repo; the hash lets --uninstall skip
    # files the user has since edited.
    local root f rel h
    root="$(cd "$(dirname "$manifest_path")/.." && pwd)"
    printf '# format: sha256<TAB>relative-path\n'
    while [[ $# -gt 0 ]]; do
      f="$1"; rel="${f#"$root"/}"
      h="$(manifest_hash "$f")"
      printf '%s\t%s\n' "$h" "$rel"
      shift
    done
  } > "$manifest_path"

  echo "[OK] Wrote uninstall manifest: $manifest_path"
}

# ----------------------------------------------------------------------------
# manifest_rows <manifest-path>
#
# Normalises every manifest format to "hash<TAB>rel<TAB>origin<TAB>backup":
#   legacy v0.x  <absolute path>                    → -     rel created -
#   v1           <sha256><TAB><rel>                 → sha   rel created -
#   v2           <sha256|-><TAB><rel><TAB><origin><TAB><backup rel|->
# origin is created | overwritten | dir. Every rel (and backup) is checked
# with safe_relative_path first; returns 1 on any unsafe or malformed
# row. (v1 readers see a v2 rel containing tabs and refuse it — safe.)
# ----------------------------------------------------------------------------
manifest_rows() {
  local manifest_path="$1" root line hash rel origin backup rest out=""
  root="$(cd "$(dirname "$manifest_path")/.." && pwd)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    origin="created"; backup="-"
    if [[ "$line" == *$'\t'* ]]; then
      hash="${line%%$'\t'*}"; rest="${line#*$'\t'}"
      if [[ "$rest" == *$'\t'* ]]; then
        rel="${rest%%$'\t'*}"; rest="${rest#*$'\t'}"
        origin="${rest%%$'\t'*}"; backup="${rest#*$'\t'}"
        [[ "$backup" == *$'\t'* ]] && { echo "[FAIL] Malformed manifest row: $line" >&2; return 1; }
      else
        rel="$rest"
      fi
    else
      [[ "$line" == "$root/"* ]] || { echo "[FAIL] Manifest path is outside target: $line" >&2; return 1; }
      hash="-"; rel="${line#"$root"/}"
    fi
    case "$origin" in created|overwritten|dir) ;; *)
      echo "[FAIL] Unknown manifest origin '${origin}' for: $rel" >&2; return 1 ;;
    esac
    safe_relative_path "$root" "$rel" || { echo "[FAIL] Unsafe manifest path: $rel" >&2; return 1; }
    if [[ "$backup" != "-" ]]; then
      safe_relative_path "$root" "$backup" || { echo "[FAIL] Unsafe manifest backup path: $backup" >&2; return 1; }
    fi
    out="${out}${hash}"$'\t'"${rel}"$'\t'"${origin}"$'\t'"${backup}"$'\n'
  done < "$manifest_path"
  printf '%s' "$out"
}

# ----------------------------------------------------------------------------
# manifest_uninstall <manifest-path>
#
# Reverses a stamp as one transaction (lib/txn.sh): files still matching their
# recorded hash are removed — or, when the stamp overwrote a file with
# --force, the saved original is restored. Modified files are kept. The
# manifest is removed last (the commit point); any failure before that rolls
# every change back. Then directories the stamp created are pruned if empty.
# Returns 1 when refused (missing manifest, unsafe row), 2 on a failed
# (rolled-back) or locked run.
# ----------------------------------------------------------------------------
manifest_uninstall() {
  local manifest_path="$1"

  if [[ ! -f "$manifest_path" ]]; then
    echo "[FAIL] Manifest not found: $manifest_path"
    echo "       No record of what was stamped here. Either the scaffolder"
    echo "       was never run in this directory, or the manifest was removed"
    echo "       manually. Falling back to .claude.bak/ restore is the only"
    echo "       way to reverse a stamp without a manifest."
    return 1
  fi

  echo "[INFO] Reading manifest: $manifest_path"
  local root rows manifest_rel
  root="$(cd "$(dirname "$manifest_path")/.." && pwd)"
  manifest_rel="${manifest_path#"$root"/}"
  # Validate the complete list before touching even one file.
  rows="$(manifest_rows "$manifest_path")" || return 1
  safe_relative_path "$root" "$manifest_rel" || { echo "[FAIL] Unsafe manifest location: $manifest_path" >&2; return 1; }

  txn_begin "$root" ".claude/.scaffold-tmp" scaffold "${MANIFEST_FORCE_UNLOCK:-0}" || return 2
  # shellcheck disable=SC2034  # read by lib/txn.sh
  TXN_APPLYING=1

  local hash rel origin backup removed=0 restored=0 kept=0 gone=0 dirs="" d
  while IFS=$'\t' read -r hash rel origin backup; do
    [[ -z "$rel" ]] && continue
    if [[ "$origin" == dir ]]; then
      dirs="${dirs}${rel}"$'\n'; continue
    fi
    if [[ ! -e "$root/$rel" ]]; then
      gone=$((gone + 1)); continue
    fi
    if [[ "$hash" != "-" && "$(manifest_hash "$root/$rel")" != "$hash" ]]; then
      echo "[WARN] kept (modified since stamping): ${rel}"
      kept=$((kept + 1)); continue
    fi
    if [[ "$origin" == overwritten ]]; then
      if [[ "$backup" != "-" && -f "$root/$backup" ]]; then
        txn_copy_in "$root/$backup" "$rel" || { txn_on_exit 2; return 2; }
        restored=$((restored + 1))
      else
        echo "[WARN] kept ${rel}: it replaced one of your files and the backup ${backup} is missing"
        kept=$((kept + 1))
      fi
      continue
    fi
    txn_remove "$rel" || { txn_on_exit 2; return 2; }
    removed=$((removed + 1))
  done <<< "$rows"

  # Commit point: the manifest goes last.
  txn_remove "$manifest_rel" || { txn_on_exit 2; return 2; }
  txn_end
  echo "[OK] Removed ${removed} file(s), restored ${restored} original(s) (${gone} already gone, ${kept} kept)"

  # v1/legacy manifests record no directories: prune ancestors of every
  # listed file, deepest first. v2 lists the directories the stamp created.
  if [[ -z "$dirs" ]]; then
    while IFS=$'\t' read -r hash rel origin backup; do
      [[ -z "$rel" ]] && continue
      d="${rel%/*}"
      while [[ "$d" != "$rel" && -n "$d" ]]; do
        dirs="${dirs}${d}"$'\n'
        [[ "$d" == */* ]] || break
        d="${d%/*}"
      done
    done <<< "$rows"
  fi
  local pruned=0
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    rmdir "$root/$d" 2>/dev/null && pruned=$((pruned + 1))
  done < <(printf '%s' "$dirs" | LC_ALL=C sort -u | LC_ALL=C sort -r)
  echo "[OK] Pruned ${pruned} now-empty directories"

  # Best-effort prune of .claude/ (the other dispatcher's manifest may remain).
  rmdir "$(dirname "$manifest_path")" 2>/dev/null || true
  echo "[OK] Removed manifest"
  return 0
}
