#!/bin/bash
# ============================================================================
# manifest.sh — uninstall manifest helpers
#
# Each dispatcher (init.sh, init-scaffold.sh) records the files it stamped
# into a per-dispatcher manifest under .claude/. A later --uninstall call
# reads that manifest and reverses the operation: rm each listed file, then
# prune any now-empty parent directories, then drop the manifest itself.
#
# Two separate manifests so the two scaffolders coexist in the same workspace
# and uninstall independently:
#   .claude/.scaffold-manifest-rules.txt      (written by init.sh)
#   .claude/.scaffold-manifest-scaffold.txt   (written by init-scaffold.sh)
#
# Manifest format:
#   # ... arbitrary comment / metadata lines beginning with '#'
#   <absolute-path-to-file>
#   <absolute-path-to-file>
#   ...
#
# Usage:
#   source "${SCRIPT_DIR}/lib/manifest.sh"
#   manifest_write "${TARGET_DIR}/.claude/.scaffold-manifest-foo.txt" \
#                  "Generated by foo.sh" \
#                  "Platform: $PLATFORM" \
#                  -- \
#                  "${CREATED_FILES[@]}"
#   manifest_uninstall "${TARGET_DIR}/.claude/.scaffold-manifest-foo.txt"
# ============================================================================

set -euo pipefail

# ----------------------------------------------------------------------------
# manifest_write <manifest-path> <header-1> [<header-N>...] -- <file-1> [<file-N>...]
#
# Header lines are emitted prefixed with '# ' for readability + so the
# uninstall reader skips them. Then '--' marks the end of headers and the
# remaining positional args are the absolute file paths to record.
# ----------------------------------------------------------------------------
manifest_write() {
  local manifest_path="$1"
  shift

  mkdir -p "$(dirname "$manifest_path")"

  {
    while [[ $# -gt 0 && "$1" != "--" ]]; do
      printf '# %s\n' "$1"
      shift
    done
    # Consume the '--' separator if present.
    [[ "${1:-}" == "--" ]] && shift

    while [[ $# -gt 0 ]]; do
      printf '%s\n' "$1"
      shift
    done
  } > "$manifest_path"

  echo "[OK] Wrote uninstall manifest: $manifest_path"
}

# ----------------------------------------------------------------------------
# manifest_uninstall <manifest-path>
#
# Reads the manifest, rm's every listed file, prunes now-empty parent dirs
# (in reverse-depth order), then deletes the manifest itself. Exits non-zero
# if the manifest doesn't exist.
# ----------------------------------------------------------------------------
manifest_uninstall() {
  local manifest_path="$1"

  if [[ ! -f "$manifest_path" ]]; then
    echo "[FAIL] Manifest not found: $manifest_path"
    echo "       No record of what was stamped here. Either the scaffolder"
    echo "       was never run in this directory, or the manifest was removed"
    echo "       manually. Falling back to .claude.bak/ restore is the only"
    echo "       way to reverse a stamp without a manifest."
    return 1
  fi

  echo "[INFO] Reading manifest: $manifest_path"

  # Collect non-comment, non-blank lines into the files array.
  local files=()
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    files+=("$line")
  done < "$manifest_path"

  if [[ ${#files[@]} -eq 0 ]]; then
    echo "[WARN] Manifest is empty — nothing to remove."
    rm -f "$manifest_path"
    return 0
  fi

  echo "[INFO] Manifest lists ${#files[@]} files to remove"

  local removed=0
  local skipped=0
  local f
  for f in "${files[@]}"; do
    if [[ -f "$f" ]]; then
      rm -f "$f"
      removed=$((removed + 1))
    else
      skipped=$((skipped + 1))
    fi
  done
  echo "[OK] Removed ${removed} files (${skipped} already gone)"

  # Prune empty parent dirs. Walk up the ancestry of every removed file: for
  # /a/b/c/file.txt we try to rmdir /a/b/c, then /a/b, then /a — sort -r
  # gives deepest-first so the inner dir is empty before the outer dir is
  # tried. Stop walking up at the manifest's target root (the parent of
  # `.claude/`) — we don't want to nuke the workspace dir itself.
  local ancestor_dirs=()
  local f d
  for f in "${files[@]}"; do
    d="$(dirname "$f")"
    while [[ -n "$d" && "$d" != "." && "$d" != "/" ]]; do
      ancestor_dirs+=("$d")
      d="$(dirname "$d")"
    done
  done
  local dirs_unique
  dirs_unique=$(printf '%s\n' "${ancestor_dirs[@]}" | sort -u | sort -r)
  local pruned=0
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    if rmdir "$d" 2>/dev/null; then
      pruned=$((pruned + 1))
    fi
  done <<< "$dirs_unique"
  echo "[OK] Pruned ${pruned} now-empty directories"

  # Remove the manifest itself, then best-effort prune its parent directory
  # (typically .claude/). If the parent is non-empty (e.g. the OTHER
  # dispatcher's manifest still lives there), rmdir silently fails — fine.
  rm -f "$manifest_path"
  rmdir "$(dirname "$manifest_path")" 2>/dev/null || true
  echo "[OK] Removed manifest"
  return 0
}
