#!/usr/bin/env bash
# === harness release: regenerate harness/manifest.tsv ===
# The manifest lists every vendored harness file with:
#   src (relative to harness/)  dest (relative to project)  file_version  sha256  profiles
# file_version is the release in which that file's content last changed: it is
# carried forward from the previous manifest while the content hash is unchanged
# and set to the current VERSION when the content changes. This keeps project
# upgrade diffs minimal and makes stale files identifiable per file.
#
# Usage:
#   bash scaffold/lib/release.sh           # rewrite harness/manifest.tsv
#   bash scaffold/lib/release.sh --check   # exit 1 if the manifest is out of date
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
H="$ROOT/harness"
# shellcheck source=../../harness/bin/harness-lib.sh
source "$H/bin/harness-lib.sh"

check=0
[[ "${1:-}" == "--check" ]] && check=1
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || hc_die "VERSION '$VERSION' is not semver"

MANIFEST="$H/manifest.tsv"
PROFILES="$H/profiles.tsv"

release_dest() { # src (relative to harness/) -> dest (relative to project); empty = not shipped
  case "$1" in
    core/*)             echo ".claude/rules/harness/${1#core/}" ;;
    rules/*)            echo ".claude/rules/harness/${1#rules/}" ;;
    skills/*)           echo ".claude/skills/${1#skills/}" ;;
    agents/*)           echo ".claude/agents/${1#agents/}" ;;
    hooks/*|snippets/*|bin/*) echo ".claude/harness/$1" ;;
    README.md)          echo ".claude/harness/README.md" ;;
    settings.base.json) echo ".claude/harness/settings.base.json" ;;
    dotfiles/harness.gitignore) echo ".claude/harness/.gitignore" ;;
    *) echo "" ;;
  esac
}

release_profiles() { # src -> profiles (first matching glob in profiles.tsv)
  local src="$1" glob prof
  while IFS=$'\t' read -r glob prof; do
    [[ -z "$glob" || "$glob" == \#* ]] && continue
    # shellcheck disable=SC2053  # intentional glob match
    if [[ "$src" == $glob ]]; then echo "$prof"; return 0; fi
  done < "$PROFILES"
  echo "all"
}

tmp="$(mktemp -d "${TMPDIR:-/tmp}/harness-release.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

(cd "$H" && find . -type f ! -name manifest.tsv ! -name profiles.tsv ! -path './.tmp/*' \
  | sed 's#^\./##' | LC_ALL=C sort) > "$tmp/files"

# Refuse junk that must never ship.
if grep -E '(^|/)(\.venv|__pycache__|node_modules)/|\.pyc$|(^|/)\.env$|(^|/)\.env\.[^/]*$' "$tmp/files" \
     | grep -vE '\.env\.(example|template|sample)$' > "$tmp/junk"; then
  hc_die "refusing to release junk files: $(tr '\n' ' ' < "$tmp/junk")"
fi

hc_hash_list "$H" < "$tmp/files" > "$tmp/hashes"

{
  echo "# harness manifest — generated by scaffold/lib/release.sh; do not edit by hand."
  echo "# harness_version	$VERSION"
  echo "#src	dest	file_version	sha256	profiles"
  while IFS=$'\t' read -r sha src; do
    dest="$(release_dest "$src")"
    if [[ -z "$dest" ]]; then
      hc_warn "not shipped (no dest mapping): $src"
      continue
    fi
    ver="$VERSION"
    if [[ -f "$MANIFEST" ]]; then
      prev="$(awk -F'\t' -v s="$src" -v h="$sha" '$1 == s && $4 == h { print $3; exit }' "$MANIFEST")"
      [[ -n "$prev" ]] && ver="$prev"
    fi
    printf '%s\t%s\t%s\t%s\t%s\n' "$src" "$dest" "$ver" "$sha" "$(release_profiles "$src")"
  done < "$tmp/hashes"
} > "$tmp/manifest"

if [[ $check -eq 1 ]]; then
  if [[ -f "$MANIFEST" ]] && diff -q <(tr -d '\r' < "$MANIFEST") "$tmp/manifest" >/dev/null; then
    hc_ok "manifest is up to date (v$VERSION, $(grep -vc '^#' "$tmp/manifest") files)"
    exit 0
  fi
  hc_fail "harness/manifest.tsv is stale — run: bash scaffold/lib/release.sh"
  diff <(tr -d '\r' < "$MANIFEST" 2>/dev/null || true) "$tmp/manifest" | head -20 >&2 || true
  exit 1
fi

mv "$tmp/manifest" "$MANIFEST"
hc_ok "wrote harness/manifest.tsv (v$VERSION, $(grep -vc '^#' "$MANIFEST") files)"
